version: '3'
services:
  app:   
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
   
    environment:
      - NODE_ENV=development
    volumes: 
      - ./:/app
    depends_on: 
      - postgres
      - adminer 

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mydb
    ports: 
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
networks:
  app-network: